package com.aimportal.DataAccess.Constant;

/*for compatiable with JRE1.6*/
public enum JDBCType {
    Bit,TINYINT,SMALLINT,INTEGER,BIGINT,
    FLOAT,REAL,DOUBLE,NUMERIC, DECIMAL,
    CHAR,VARCHAR,LONGVARCHAR,DATE,TIME,
    TIMESTAMP,BINARY,VARBINARY,LONGVARBINARY,NULL,
    OTHER,JAVA_OBJECT,DISTINCT,STRUCT,ARRAY,
    BLOB,CLOB,REF,DATALINK,BOOLEAN,ROWID,NCHAR,NVARCHAR,LONGNVARCHAR,NCLOB,SQLXML;
}
